CREATE DATABASE IF NOT EXISTS roulette;

USE roulette;

CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE,
  balance FLOAT
);

CREATE TABLE IF NOT EXISTS rounds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  winningNumber TINYINT UNSIGNED,
  state TINYINT UNSIGNED
);